### ISSUE TITLE
qcom_display

### ISSUE THREAD

**Issue by ghost5825** [CandyRoms/candy#1]
in the default manifest, hardware_qcom_display wont sync because its missing the revision tag its in the aospb repo, so i checked and it looks like it should be mm6.0. I just started all of this so not sure if im correct but if so thought i'd offer my solution.
![screenshot from 2016-05-21 00 17 18](https://cloud.githubusercontent.com/assets/13989941/15446836/6d398b24-1ee9-11e6-9e1f-4af5b989c48e.png)

**Comment by IronSharpensIron2717** [comment]
Should sync just fine because mm6.0 is defined as default branch here https://github.com/CandyRoms/candy/blob/c6/default.xml#L38

Also we don't except pull requests, please use our Gerrit 
https://gerrit.bbqdroid.org/#/q/status:open
