### ISSUE TITLE
Building Unofficial Rom

### ISSUE THREAD

**Issue by Zaviyar786** [CandyRoms/candy#10]
Dear Team,
Newbie Here Need Some Guidance.. Facing Error While Compiling
https://del.dog/jahajolido.json

**Comment by NoSpamDan** [comment]
@HeartStealer786 Device?

**Comment by NoSpamDan** [comment]
@NoSpamDan If you need help, you should come to https://tinyurl.com/yy4xo8c8 on Telegram.

**Comment by Zaviyar786** [comment]
redmi note 5 pro whyred ok i will join tnx

**Comment by NoSpamDan** [comment]
@HeartStealer786 GitHub is not the place for build problems and help.  Come to TG as I said.  There are plenty of people there who can help.
