### ISSUE TITLE
Error: .java error when building camera2

### ISSUE THREAD

**Issue by Dhina17** [CandyRoms/candy#12]
Error https://del.dog/qogututumi
How to fix this

**Comment by NoSpamDan** [comment]
> Error https://del.dog/qogututumi
> How to fix this

Ask in our public Telegram chat https://tinyurl.com/yy4xo8c8

**Comment by NoSpamDan** [comment]
@NoSpamDan Closed and sent to public Candy channel

**Comment by Dhina17** [comment]
Ok
