### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [CandyRoms/candy#13]
Hello! I collect firmware on android 10 and get this error, how to fix it?

FAILED: out/target/common/obj/APPS/Snap_intermediates/classes-full-debug.jar
/bin/bash -c "(rm -f out/target/common/obj/APPS/Snap_intermediates/classes-full-debug.jar ) && (rm -rf out/target/common/obj/APPS/Snap_intermediates/classes out/target/common/obj/APPS/Snap_intermediates/anno ) && (mkdir -p out/target/common/obj/APPS/Snap_intermediates/ ) && (mkdir -p out/target/common/obj/APPS/Snap_intermediates/classes out/target/common/obj/APPS/Snap_intermediates/anno ) && (out/soong/host/linux-x86/bin/zipsync -d out/target/common/obj/APPS/Snap_intermediates/srcjars -l out/target/common/obj/APPS/Snap_intermediates/srcjar-list -f \"*.java\"  out/target/common/obj/APPS/Snap_intermediates/renderscript/rs.srcjar out/target/common/obj/APPS/Snap_intermediates/aapt2.srcjar ) && (if [ -s out/target/common/obj/APPS/Snap_intermediates/java-source-list -o -s out/target/common/obj/APPS/Snap_intermediates/srcjar-list ] ; then out/soong/host/linux-x86/bin/soong_javac_wrapper  prebuilts/jdk/jdk9/linux-x86/bin/javac -Xmaxerrs 9999999 -encoding UTF-8 -sourcepath \"\" -g -XDskipDuplicateBridges=true -XDstringConcat=inline -encoding UTF-8   -bootclasspath out/target/common/obj/JAVA_LIBRARIES/core.platform.api.stubs_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/ext_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/framework_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/updatable_media_stubs_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/core-lambda-stubs_intermediates/classes-header.jar  -classpath out/target/common/obj/JAVA_LIBRARIES/xmp_toolkit_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/zxing-core_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/qreader-core_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/qreader-zxing_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/android-support-v13_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/android-support-v4_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/android-support-v7-recyclerview_intermediates/classes-header.jar:out/target/common/obj/JAVA_LIBRARIES/androidx.heifwriter_heifwriter_intermediates/classes-header.jar  -d out/target/common/obj/APPS/Snap_intermediates/classes -s out/target/common/obj/APPS/Snap_intermediates/anno  -source 1.8 -target 1.8  \\@out/target/common/obj/APPS/Snap_intermediates/java-source-list \\@out/target/common/obj/APPS/Snap_intermediates/srcjar-list || ( rm -rf out/target/common/obj/APPS/Snap_intermediates/classes ; exit 41 ) fi ) && (prebuilts/jdk/jdk9/linux-x86/bin/jar -cf out/target/common/obj/APPS/Snap_intermediates/classes-full-debug.jar     @<(find out/target/common/obj/APPS/Snap_intermediates/classes -type f | sort | build/soong/scripts/jar-args.sh out/target/common/obj/APPS/Snap_intermediates/classes; echo \"-C out/empty .\") )"
Picked up _JAVA_OPTIONS: -Xms6G -Xmx6G
packages/apps/Snap/src/com/android/camera/util/CameraUtil.java:252: error: cannot find symbol
                com.android.internal.R.integer.config_deviceHardwareKeys);
                                              ^
  symbol:   variable config_deviceHardwareKeys
  location: class integer
1 error

**Comment by IronSharpensIron2717** [comment]
The easy way past it? `rm - rf packages/apps/Snap`

**Comment by Ingvarr71** [comment]
> The easy way past it? `rm - rf packages/apps/Snap`

Then the firmware will be without a camera?

**Comment by IronSharpensIron2717** [comment]
> > The easy way past it? `rm - rf packages/apps/Snap`
> 
> Then the firmware will be without a camera?

Na should build camera2 then 

Or you can pick this 
https://github.com/CarbonROM/android_packages_apps_Snap/commit/efbe45136b99d80c989eb01ef4e9275228aeff65
