### ISSUE TITLE
1

### ISSUE THREAD

**Issue by Ingvarr71** [CandyRoms/candy#15]
Hello! I get an error when assembling the firmware, how can I fix it?

[ 75% 81949/108324] target  C: android.hardware.power@1.2-service-qti <= vendor/qcom/opensource/power/power-660.c
FAILED: out/target/product/tulip/obj/EXECUTABLES/android.hardware.power@1.2-service-qti_intermediates/power-660.o
/bin/bash -c "PWD=/proc/self/cwd /usr/bin/ccache prebuilts/clang/host/linux-x86/clang-r353983c1/bin/clang 	-I external/libxml2/include -I external/icu/icu4c/source/common -I vendor/qcom/opensource/power -I out/target/product/tulip/obj/EXECUTABLES/android.hardware.power@1.2-service-qti_intermediates -I out/target/product/tulip/gen/EXECUTABLES/android.hardware.power@1.2-service-qti_intermediates \$(cat out/target/product/tulip/obj/EXECUTABLES/android.hardware.power@1.2-service-qti_intermediates/import_includes)   -isystem out/target/product/tulip/obj/include -c  -Werror=implicit-function-declaration -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fno-strict-aliasing -fdebug-prefix-map=/proc/self/cwd= -D__compiler_offsetof=__builtin_offsetof -faddrsig -Wimplicit-fallthrough -Werror=int-conversion -Wno-reserved-id-macro -Wno-format-pedantic -Wno-unused-command-line-argument -fcolor-diagnostics -Wno-zero-as-null-pointer-constant -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=date-time -Werror=format-security -nostdlibinc -march=armv8-a -mcpu=kryo -target aarch64-linux-android -Bprebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/aarch64-linux-android/bin   -std=gnu99    -Wall -Wextra -Werror -DTAP_TO_WAKE_NODE=\\\"\"/proc/wake_node\"\\\" -DINTERACTION_BOOST -D__ANDROID_API__=29 -D__ANDROID_VNDK__ -fPIE -D_USING_LIBCXX -DANDROID_STRICT   -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-tautological-unsigned-enum-zero-compare -Wno-tautological-unsigned-zero-compare -Wno-c++98-compat-extra-semi -Wno-return-std-move-in-c++11 -MD -MF out/target/product/tulip/obj/EXECUTABLES/android.hardware.power@1.2-service-qti_intermediates/power-660.d -o out/target/product/tulip/obj/EXECUTABLES/android.hardware.power@1.2-service-qti_intermediates/power-660.o vendor/qcom/opensource/power/power-660.c"
vendor/qcom/opensource/power/power-660.c:209:9: error: non-void function 'process_interaction_hint' should return a value [-Wreturn-type]
        return;
        ^
1 error generated.

**Comment by NoSpamDan** [comment]
Link your device tree please

**Comment by Ingvarr71** [comment]
I don't have a tree for github

**Comment by Ingvarr71** [comment]
I have already collected the firmware before
https://4pda.ru/forum/index.php?s=&showtopic=930547&view=findpost&p=96689923

**Comment by Ingvarr71** [comment]
there was no such mistake

**Comment by NoSpamDan** [comment]
@Ingvarr71 Then link to it, wherever it exists

**Comment by Ingvarr71** [comment]
https://drive.google.com/file/d/1NbM-emylcVLEaZ796kFAh19aG-vL_e3K/view?usp=sharing

**Comment by NoSpamDan** [comment]
You really need to push that to Github with authorship.  Looks like missing/incorrect power HAL support.

**Comment by Ingvarr71** [comment]
Before that, I collected without errors

**Comment by NoSpamDan** [comment]
@Ingvarr71 You mean synced and built?
