### ISSUE TITLE
Error when Building for Bullhead

### ISSUE THREAD

**Issue by Yaznas** [CandyRoms/candy#9]
How do i solve this error during compiling process?

https://pastebin.com/0wPY8wqi

**Comment by IronSharpensIron2717** [comment]
tells you whats wrong, remove line 426 in file device/lge/bullhead/overlay/frameworks/base/core/res/res/values/config.xm

**Comment by Yaznas** [comment]
@rc420head 
did what u said! new to android rom building

https://pastebin.com/wWrJ5yuk

**Comment by EyeCantCU** [comment]
You should ensure you can build the kernel standalone first. Try this:

export ARCH=arm64
make bullhead_defconfig
make CROSS_COMPILE=/path/to/toolchain

If the zImage compiles then get back to me... Certainly not us though. I'm going to close this for now. Feel free to contact me on hangouts at certifiedblyndguy@gmail.com. I'm more than happy to help (within reason).

**Comment by Yaznas** [comment]
I get error during kernel compilation! What lines need to be changed? Also, I cant seem to message you on hangouts.
https://pastebin.com/HyWFBJMG

**Comment by IronSharpensIron2717** [comment]
You're getting permission denied, are you building on a server? Separate drive? Did you create the source folder using sudo? Try just mka bootimage

**Comment by Yaznas** [comment]
@rc420head im building only hdd in VM virtual box ubuntu 16.04... i dont think i used sudo for the source folder only mkdir
